name: 'Webtechnologie'
version: 0.0.1
description: Implementation of the Game Namcap.
#author: Sheraz Azad, Malte Grebe & Niklas Klatt

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- dart_to_js_script_rewriter