name: snakedart
version: 0.1.0
author: Nane Kratzke <nane@nkode.io>
description: Dart implementation of the famous Snake Game.
homepage: https://github.com/nkratzke/dartsnake
dependencies:
  browser: ">=0.10.0+2 <0.11.0"
  start:   ">=0.2.7 <0.3.0"
