library pacmanModelLib;

// Imports
import 'dart:async';
import 'dart:convert';
import 'dart:html';
import 'package:Webtechnologie/pacmanControllerLib.dart';
// Parts
part 'src/model/Blinky.dart';
part 'src/model/Cherry.dart';
part 'src/model/Clyde.dart';
part 'src/model/Directions.dart';
part 'src/model/Environment.dart';
part 'src/model/GameElement.dart';
part 'src/model/Ghost.dart';
part 'src/model/Inky.dart';
part 'src/model/Item.dart';
part 'src/model/Level.dart';
part 'src/model/LevelLoader.dart';
part 'src/model/Pacman.dart';
part 'src/model/PacmanGameModel.dart';
part 'src/model/Pill.dart';
part 'src/model/Pinky.dart';
part 'src/model/PowerPill.dart';
part 'src/model/Score.dart';
part 'src/model/Tile.dart';
part 'src/model/Types.dart';
part 'src/model/Apple.dart';
